**Exploring Data**

In [3]:

import pandas as pd
import numpy as np

In [4]:
root_X = r"C:\Users\Haison\Documents\movie_classifier\data\processed\X.csv"
root_Y = r"C:\Users\Haison\Documents\movie_classifier\data\processed\Y.csv"
X = pd.read_csv(root_X)
Y = pd.read_csv(root_Y)

In [5]:
#Shape of dataset in X
X.shape

(3428, 3705)

In [6]:
#Shape of dataset in Y
Y.shape

(3428, 1)

In [7]:
X

,0,1,2,3,4,5,6,7,8,9,...,3695,3696,3697,3698,3699,3700,3701,3702,3703,3704
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,5,5,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,3,5,0,0,0,0,4,0,...,0,0,0,0,0,0,0,0,0,0
3,0,5,5,0,0,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3423,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3424,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3425,0,3,4,4,5,0,0,5,0,0,...,0,0,0,0,0,0,0,0,0,0
3426,0,0,0,0,0,0,4,0,4,0,...,0,0,0,0,0,0,0,0,0,0
3427,0,0,0,0,0,0,0,0,5,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
Y.describe().T

        count      mean       std  min  25%  50%  75%  max
label  3428.0  0.832264  0.373686  0.0  1.0  1.0  1.0  1.0

In [9]:
X.isnull().sum()

0       0
1       0
2       0
3       0
4       0
       ..
3700    0
3701    0
3702    0
3703    0
3704    0
Length: 3705, dtype: int64

In [10]:
Y.isnull().sum()

label    0
dtype: int64

In [34]:
import pandas as pd
import chardet

def cargar_peliculas(movies_path="C:/Users/Haison/Documents/movie_classifier/data/raw/movies.dat"):
    try:
        
        with open(movies_path, "rb") as f:
            result = chardet.detect(f.read(5000))  
            encoding_detectado = result["encoding"]

        df_movies = pd.read_csv(
            movies_path, sep="::", engine="python", header=None,
            names=["MovieID", "Title", "Genres"], encoding=encoding_detectado
        )
        return df_movies

    except FileNotFoundError:
        print(f"No se encontró el archivo en {movies_path}")
        return None
    
df_movies = cargar_peliculas()
df_movies.head(n=10)

   MovieID                               Title                        Genres
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy
5        6                         Heat (1995)         Action|Crime|Thriller
6        7                      Sabrina (1995)                Comedy|Romance
7        8                 Tom and Huck (1995)          Adventure|Children's
8        9                 Sudden Death (1995)                        Action
9       10                    GoldenEye (1995)     Action|Adventure|Thriller

In [28]:
df_movies.shape

(3883, 3)

In [29]:
df_movies.info

<bound method DataFrame.info of       MovieID                               Title  \
0           1                    Toy Story (1995)
1           2                      Jumanji (1995)
2           3             Grumpier Old Men (1995)
3           4            Waiting to Exhale (1995)
4           5  Father of the Bride Part II (1995)
...       ...                                 ...
3878     3948             Meet the Parents (2000)
3879     3949          Requiem for a Dream (2000)
3880     3950                    Tigerland (2000)
3881     3951             Two Family House (2000)
3882     3952               Contender, The (2000)

                            Genres
0      Animation|Children's|Comedy
1     Adventure|Children's|Fantasy
2                   Comedy|Romance
3                     Comedy|Drama
4                           Comedy
...                            ...
3878                        Comedy
3879                         Drama
3880                         Drama
3881                         Drama
3882                Drama|Thriller

[3883 rows x 3 columns]>

In [30]:
df_movies.columns

Index(['MovieID', 'Title', 'Genres'], dtype='object')

In [42]:
import re
lista = []
for i in df_movies["Title"].head(n=10):
    patron = r"\((.*?)\)"
    lista.extend((re.findall(patron, i)))
lista

['1995',
 '1995',
 '1995',
 '1995',
 '1995',
 '1995',
 '1995',
 '1995',
 '1995',
 '1995']